export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const AUTH_CHECK_REQUEST = 'AUTH_CHECK_REQUEST'
export const AUTH_CHECK_SUCCESS = 'AUTH_CHECK_SUCCESS'
export const AUTH_CHECK_FAILURE = 'AUTH_CHECK_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'

export const LOAD_CURRENT_USER_REQUEST = 'LOAD_CURRENT_USER_REQUEST'
export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS'
export const LOAD_CURRENT_USER_FAILURE = 'LOAD_CURRENT_USER_FAILURE'
